version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-sam-example-cron"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uuf9mejgtcto"
s3_prefix = "stack-sam-example-cron"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = true
image_repositories = []
